; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.21, 2005/04/09, Denki release)
; on Sat Apr 21 14:00:24 2007
;

HUC	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

  .data
  .bank CONST_BANK
  .org $4400
 _sound_dat:
	dw	sound_data_table	; 0
	dw	loop_point_table	; 1
	dw	softenve_table		; 2
	dw	softenve_lp_table	; 3
	dw	pitchenve_table		; 4
	dw	pitchenve_lp_table	; 5
	dw	lfo_data		    ; 6
	dw	sound_data_bank		; 7
	dw	loop_point_bank		; 8
	dw	arpeggio_table		; 9
	dw	arpeggio_lp_table	; 10
_pcewav:
	dw	pce_data_table
_xpcmdata
	dw	xpcm_data
;	.include "songdata.h"
	.bank CONST_BANK
	.include "effect.h"
;------------------------------
; PCM timer routines
	.code
	.bank START_BANK
_timer_pcm
	pha
	phx
	phy
	lda	<__temp
	sta	<__tmr_tmp
	lda	<__temp+1
	sta	<__tmr_tmp+1
;	lda	<__temp+2
;	sta	<__tmr_tmp+2
;	lda	<__temp+3
;	sta	<__tmr_tmp+3
	lda	<__ptr
	sta	<__tmr_ptr
	lda	<__ptr+1
	sta	<__tmr_ptr+1
	lda	<_bx
	sta	<__tmr_bx
	lda	<_bx+1
	sta	<__tmr_bx+1
	tma	#page(_pcm_intr)
	pha
	map	_pcm_intr
	jsr	_pcm_intr
	pla
	tam	#page(_pcm_intr)
	lda	<__tmr_tmp
	sta	<__temp
	lda	<__tmr_tmp+1
	sta	<__temp+1
;	lda	<__tmr_tmp+2
;	sta	<__temp+2
;	lda	<__tmr_tmp+3
;	sta	<__temp+3
	lda	<__tmr_ptr
	sta	<__ptr
	lda	<__tmr_ptr+1
	sta	<__ptr+1
	lda	<__tmr_bx
	sta	<_bx
	lda	<__tmr_bx+1
	sta	<_bx+1
	sta   irq_status
	cli
	ply
	plx
	pla
	rti
_vsync_drv
	lda	<__temp
	sta	<__vs_tmp
	lda	<__temp+1
	sta	<__vs_tmp+1
	lda	<__ptr
	sta	<__vs_ptr
	lda	<__ptr+1
	sta	<__vs_ptr+1
	lda	<_bx
	sta	<__vs_bx
	lda	<_bx+1
	sta	<__vs_bx+1
	tma	#page(_drv_intr)
	pha
	map	_drv_intr
	jsr	_drv_intr
	pla
	tam	#page(_drv_intr)
	lda	<__vs_tmp
	sta	<__temp
	lda	<__vs_tmp+1
	sta	<__temp+1
	lda	<__vs_ptr
	sta	<__ptr
	lda	<__vs_ptr+1
	sta	<__ptr+1
	lda	<__vs_bx
	sta	<_bx
	lda	<__vs_bx+1
	sta	<_bx+1
	rts
           .zp
__tmr_tmp   .ds 8
__tmr_ptr   .ds 2
__tmr_bx    .ds 2
__vs_tmp   .ds 2
__vs_ptr   .ds 2
__vs_bx    .ds 2
	; restore segment and bank
	.code
	.bank START_BANK
	.proc _pcm_on
	__pushw
	__ldb	_xpcm_mode
	__notw
	__tstw
	__lbeq	LL2
	__ldwi	2048
	__stw	_bx
	__ldw_s	0
	  call	_poke.2
	__ldwi	2052
	__stw	_bx
	__ldwi	223
	  call	_poke.2
	  call	_ena_irq_tmr
	__ldwi	1
	  stx	_xpcm_mode
LL2:

LL1:

	__addmi	2,__stack
	  rts
	.endp

	.proc _pcm_off
	__ldb	_xpcm_mode
	__tstw
	__lbeq	LL4
	  call	_dis_irq_tmr
	__ldwi	0
	  stx	_xpcm_mode
LL4:

LL3:

	  rts
	.endp

	.proc _pcm_set
	__pushw
	__ldwi	2048
	__stw	_bx
	__ldw_s	0
	  call	_poke.2
	__ldwi	2052
	__stw	_bx
	__ldwi	0
	  call	_poke.2
LL5:

	__addmi	2,__stack
	  rts
	.endp

	.proc _pcm_intr
	__addmi	-1,__stack
	__ldb	_xpcm_mode
	__tstw
	__lbeq	LL7
	__ldb	_xpcm_sp
	__andwi	1
	__tstw
	__lbeq	LL8
	__pea_s	0
	__ldw	_xpcm_addr
	  call	_peek
	__pushw
	__ldwi	3
	  jsr	asr
	__andwi	30
	__stbps
	__lbra	LL9
LL8:

	__pea_s	0
	__ldw	_xpcm_addr
	incw	_xpcm_addr
	  call	_peek
	__pushw
	__ldwi	1
	  jsr	asl
	__andwi	30
	__stbps
	__ldw	_xpcm_len
	__tstw
	__lbeq	LL10
	__ldw	_xpcm_len
	__subwi	1
	__stw	_xpcm_len
	__addwi	1
	__lbra	LL11
LL10:

	  call	_pcm_off
LL11:

LL9:

	__ldb	_xpcm_sp
	__pushw
	__ldwi	1
	__eorws
	  stx	_xpcm_sp
	__ldwi	2048
	__stw	_bx
	__ldwi	5
	  call	_poke.2
	__ldwi	2054
	__stw	_bx
	__ldb_s	0
	  call	_poke.2
	__ldwi	2048
	__stw	_bx
	__ldb	_reg_ch
	  call	_poke.2
LL7:

LL6:

	__addmi	1,__stack
	  rts
	.endp

    .proc _ena_irq_tmr
	smb   #2,<irq_m
	rts
	.endp
    .proc _dis_irq_tmr
	rmb   #2,<irq_m
	rts
	.endp
	.proc _set_pcmintr
	stz   irq_status
	stw   #_timer_pcm,timer_jmp
	rmb   #2,<irq_m
	lda   #0
	sta   timer_cnt
	lda   #$1
	sta   timer_ctrl
	cli
	rts
	.endp
	.proc _chg_pcmbank
	txa
	tam #3
	rts
	.endp
	.proc _init_pcmdrv
	__ldwi	0
	  stx	_xpcm_sp
	__ldwi	0
	  stx	_xpcm_sw
	__ldwi	0
	  stx	_xpcm_mode
	  call	_set_pcmintr
LL12:

	  rts
	.endp

	.proc _chg_cbank
	txa
	tam #2
	rts
	.endp
	.proc _now_cbank
	tma #2
	tax
	cla
	rts
	.endp
	.proc _def_cbank
	lda #CONST_BANK+_bank_base
	tam #2
	rts
	.endp
	.proc _mixvol
	__pushw
	__ldb	_reg_ch
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL15
	__ldb	_xpcm_sw
LL15:

	__boolw
	__tstw
	__lbeq	LL14
	__ldwi	2052
	__stw	_bx
	__ldwi	192
	__pushw
	__ldb_s	2
	__orws
	  call	_poke.2
	__lbra	LL13
LL14:

	__ldb_s	0
	__notw
	__tstw
	__lbeq	LL16
	__ldwi	2052
	__stw	_bx
	__ldwi	0
	  call	_poke.2
	__lbra	LL17
LL16:

	__ldwi	2052
	__stw	_bx
	__ldwi	128
	__pushw
	__ldb_s	2
	__orws
	  call	_poke.2
LL17:

LL13:

	__addmi	2,__stack
	  rts
	.endp

	.proc _snd_saw
	__pushw
	__addmi	-1,__stack
	__ldw_s	1
	  stx	_reg_ch
	__ldwi	2048
	__stw	_bx
	__ldw_s	1
	  call	_poke.2
	__ldwi	2052
	__stw	_bx
	__ldwi	0
	  call	_poke.2
	__stbi_s	0,0
LL19:

	__ldb_s	0
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbne	LL21
	__lbra	LL22
LL20:

	__ldb_s	0
	__addwi	1
	__stb_s	0
	__subwi	1
	__lbra	LL19
LL21:

	__ldwi	2054
	__stw	_bx
	__ldb_s	0
	  call	_poke.2
	__lbra	LL20
LL22:

	__ldwi	2053
	__stw	_bx
	__ldwi	_panpod
	__addw_s	1
	__ldb_p
	  call	_poke.2
	__ldwi	2052
	__stw	_bx
	__ldwi	128
	  call	_poke.2
LL18:

	__addmi	3,__stack
	  rts
	.endp

	.proc _snd_chg
	__pushw
	__addmi	-3,__stack
	__ldwi	_pcewav
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	5
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	0
	__ldw_s	5
	  stx	_reg_ch
	__ldwi	2048
	__stw	_bx
	__ldw_s	5
	  call	_poke.2
	__ldwi	2052
	__stw	_bx
	__ldwi	0
	  call	_poke.2
	__stbi_s	0,2
LL24:

	__ldb_s	2
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbne	LL26
	__lbra	LL27
LL25:

	__ldb_s	2
	__addwi	1
	__stb_s	2
	__subwi	1
	__lbra	LL24
LL26:

	__ldwi	2054
	__stw	_bx
	__ldw_s	0
	__ldb_p
	  call	_poke.2
	__ldw_s	0
	__incw_s	0
	__lbra	LL25
LL27:

	__ldwi	2052
	__stw	_bx
	__ldwi	128
	  call	_poke.2
LL23:

	__addmi	7,__stack
	  rts
	.endp

	.proc _set_drvintr
	stw   #_vsync_drv,vsync_hook
	smb   #4,<irq_m		; enable new code
	smb   #5,<irq_m		; disable system card code
	rts
	.endp
	.proc _drv_init
	__addmi	-2,__stack
	  call	_now_cbank
	  stx	_ch_topbank
	__ldwi	0
	__stw	_i
LL29:

	__ldw	_i
	__stw	<__temp
	__ldwi	6
	  jsr	ltzp
	__lbne	LL31
	__lbra	LL32
LL30:

	__ldw	_i
	incw	_i
	__lbra	LL29
LL31:

	__ldwi	_lfo_num
	__addw	_i
	__pushw
	__ldwi	_note_sw
	__addw	_i
	__pushw
	__ldwi	_panpod
	__addw	_i
	__pushw
	__ldwi	_pitch_sw
	__addw	_i
	__pushw
	__ldwi	255
	__stbps
	__stbps
	__stbps
	__stbps
	__ldw	_i
	__aslw
	__addwi	_seq_pos
	__pushw
	__ldwi	_sound_dat
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw	_i
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldwi	_loop_cnt
	__addw	_i
	__pushw
	__ldwi	_detune
	__addw	_i
	__pushw
	__ldw	_i
	__aslw
	__addwi	_note_envadr
	__pushw
	__ldw	_i
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__ldw	_i
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	0
	__stwps
	__stwps
	__stwps
	__stbps
	__stbps
	__ldwi	_ch_bank
	__addw	_i
	__pushw
	__ldwi	_sound_dat
	__addwi	14
	__stw	__ptr
	__ldwp	__ptr
	__addw	_i
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__lbra	LL30
LL32:

	__ldwi	0
	__stw	_i
LL33:

	__ldw	_i
	__stw	<__temp
	__ldwi	2
	  jsr	ltzp
	__lbne	LL35
	__lbra	LL36
LL34:

	__ldw	_i
	incw	_i
	__lbra	LL33
LL35:

	__ldwi	_noise_sw
	__addw	_i
	__pushw
	__ldwi	_noise_freq
	__addw	_i
	__pushw
	__ldwi	0
	__stbps
	__stbps
	__lbra	LL34
LL36:

	__ldwi	2049
	__stw	_bx
	__ldwi	255
	  call	_poke.2
	__ldwi	0
	__stw	_i
LL37:

	__ldw	_i
	__stw	<__temp
	__ldwi	6
	  jsr	ltzp
	__lbne	LL39
	__lbra	LL40
LL38:

	__ldw	_i
	incw	_i
	__lbra	LL37
LL39:

	__ldw	_i
	  call	_snd_saw
	__ldwi	_ch_cnt
	__addw	_i
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL38
LL40:

	  call	_init_pcmdrv
	  call	_set_drvintr
LL28:

	__addmi	2,__stack
	  rts
	.endp

	.proc _set_vol
	__pushw
	__ldw_s	0
	__andwi	128
	__tstw
	__lbeq	LL42
	__ldw_s	2
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	0
	__stwps
	__ldw_s	0
	__andwi	31
	  call	_mixvol
	__lbra	LL43
LL42:

	__ldw_s	0
	__andwi	127
	__stw_s	0
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw_s	2
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	4
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldb	_ch_nowbank
	  call	_chg_cbank
LL43:

LL41:

	__addmi	4,__stack
	  rts
	.endp

	.proc _set_note
	__pushw
	__addmi	-1,__stack
	__ldb_s	1
	__addwi	3
	__andwi	15
	__stb_s	0
	__ldb_s	0
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	5
	__pushw
	__ldb_s	5
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__phb	1
	__ldwi	13
	  call	_put_hex.4
	__ldwi	_seq_freq
	__pushw
	__ldb_s	5
	__aslw
	__addws
	__pushw
	__ldwi	_freq
	__pushw
	__ldb_s	4
	__andwi	15
	__aslw
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldb_s	5
	__pushw
	__ldwi	4
	  jsr	asr
	  jsr	asr
	__stwps
LL44:

	__addmi	5,__stack
	  rts
	.endp

	.proc _seq
	__pushw
	__addmi	-4,__stack
LL46:

	__ldw_s	4
	__stw	<__temp
	__ldwi	144
	  jsr	gezp
	__lbeq	LL47
	__ldw_s	4
	__stw	<__temp
	__ldwi	236
	  jsr	gezp
	__lbeq	LL48
	__ldwi	_seqproc
	__pushw
	__ldw_s	6
	__subwi	236
	__aslw
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	0
;  make jump
;  sax
  pha
  sax
  pha
  rts
SEQ_FF:
  nop
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldwi	_sound_dat
	__addwi	2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	8
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stw	_seq_ptr
	__ldwi	_sound_dat
	__addwi	16
	__stw	__ptr
	__ldwp	__ptr
	__addw_s	6
	__stw	__ptr
	__ldwp	__ptr
	  stx	_ch_nowbank
	__ldb	_ch_nowbank
	  call	_chg_cbank
		jmp endpoint
SEQ_FE:
  nop
	__ldw	_seq_ptr
	__addwi	2
	__stw	_seq_ptr
	jmp endpoint
SEQ_F9:
  nop
	__ldw	_seq_ptr
	__addwi	2
	__stw	_seq_ptr
	jmp endpoint
SEQ_FD:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_ch_vol
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	__ldw_s	6
	__pushw
	__ldw	_j
	  call	_set_vol
	jmp endpoint
SEQ_FC:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	0
	  call	_mixvol
	__ldw_s	6
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL50
	__ldb	_xpcm_sw
LL50:

	__boolw
	__tstw
	__lbeq	LL49
	  call	_pcm_off
LL49:

	__ldw_s	6
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	0
	__stwps
	__ldwi	_ch_cnt
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	__lbra	LL45
	jmp endpoint
SEQ_FB:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_lfo_num
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	__ldwi	_lfo_sw
	__addw_s	6
	__pushw
	__ldwi	0
	__stbps
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldwi	_lfo_cnt
	__addw_s	6
	__pushw
	__ldwi	_sound_dat
	__addwi	12
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw	_j
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldb	_ch_nowbank
	  call	_chg_cbank
	jmp endpoint
SEQ_FA:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw	_j
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL51
	__ldwi	_detune
	__addw_s	6
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL52
LL51:

	__ldwi	_detune
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
LL52:

	jmp endpoint
SEQ_F8:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_pitch_sw
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	jmp endpoint
SEQ_F7:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_note_sw
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	jmp endpoint
SEQ_F4:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_ch_cnt
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	jmp endpoint
SEQ_F2:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw_s	6
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL53
	__ldw	_j
	__tstw
	__lbeq	LL54
	__ldwi	_noise_sw
	__pushw
	__ldw_s	8
	__subwi	4
	__addws
	__pushw
	__ldwi	1
	__stbps
	__lbra	LL55
LL54:

	__ldwi	_noise_sw
	__pushw
	__ldw_s	8
	__subwi	4
	__addws
	__pushw
	__ldwi	0
	__stbps
	__ldwi	2055
	__stw	_bx
	__ldwi	0
	  call	_poke.2
LL55:

LL53:

	jmp endpoint
SEQ_F1:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldw_s	6
	__pushw
	__ldw	_j
	  call	_snd_chg
	__ldb	_ch_nowbank
	  call	_chg_cbank
	jmp endpoint
SEQ_F0:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_panpod
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	__ldwi	2053
	__stw	_bx
	__ldw	_j
	  call	_poke.2
	jmp endpoint
SEQ_EF:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw_s	6
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL56
	__ldw	_j
	  stx	_xpcm_sw
	__ldb	_xpcm_sw
	__tstw
	__lbeq	LL57
	__ldwi	5
	  call	_pcm_on
LL57:

LL56:

	jmp endpoint
SEQ_EE:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__pushw
	__ldw	_seq_ptr
	__addwi	1
	__ldb_p
	__pushw
	__ldwi	8
	  jsr	asl
	__orws
	__stw_s	2
	__stw	_seq_ptr
	__ldw	_j
	  call	_chg_cbank
	__ldw	_j
	  stx	_ch_nowbank
	jmp endpoint
SEQ_ED:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw	_j
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL58
	__ldwi	2057
	__stw	_bx
	__ldwi	0
	  call	_poke.2
	__lbra	LL59
LL58:

	__ldwi	2057
	__stw	_bx
	__ldw	_j
	__orwi	128
	  call	_poke.2
LL59:

	jmp endpoint
SEQ_EC:
  nop
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	2056
	__stw	_bx
	__ldw	_j
	  call	_poke.2
endpoint:
	__lbra	LL60
LL48:

	__ldw_s	4
	__stw	<__temp
	__ldwi	161
	  jsr	eqzp
	__lbeq	LL61
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_loop_cnt
	__addw_s	6
	__ldb_p
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL62
	__ldwi	_loop_cnt
	__addw_s	6
	__pushw
	__ldwi	0
	__stbps
	__ldw	_seq_ptr
	__ldb_p
	__pushw
	__ldw	_seq_ptr
	__addwi	1
	__ldb_p
	__pushw
	__ldwi	8
	  jsr	asl
	__orws
	__stw_s	2
	__stw	_seq_ptr
	__lbra	LL63
LL62:

	__ldw	_seq_ptr
	__addwi	2
	__stw	_seq_ptr
LL63:

LL61:

	__ldw_s	4
	__stw	<__temp
	__ldwi	160
	  jsr	eqzp
	__lbeq	LL64
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldb_p
	__stw_s	0
	__ldw	_seq_ptr
	__ldb_p
	__pushw
	__ldw	_seq_ptr
	__addwi	1
	__ldb_p
	__pushw
	__ldwi	8
	  jsr	asl
	__orws
	__stw_s	2
	__ldw	_seq_ptr
	__addwi	2
	__stw	_seq_ptr
	__ldwi	_loop_cnt
	__addw_s	6
	__ldb_p
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL65
	__ldwi	_loop_cnt
	__addw_s	6
	__pushw
	__ldwi	0
	__stbps
	__lbra	LL66
LL65:

	__ldwi	_loop_cnt
	__addw_s	6
	__ldb_p
	__stw	<__temp
	__ldwi	1
	  jsr	gtzp
	__lbeq	LL67
	__ldwi	_loop_cnt
	__addw_s	6
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL68
LL67:

	__ldwi	_loop_cnt
	__addw_s	6
	__pushw
	__ldw	_j
	__subwi	1
	__stbps
LL68:

	__ldw_s	2
	__stw	_seq_ptr
	__ldw_s	0
	  call	_chg_cbank
	__ldw_s	0
	  stx	_ch_nowbank
LL66:

LL64:

LL60:

	__ldw	_seq_ptr
	__ldb_p
	__stw_s	4
	__lbra	LL46
LL47:

	__ldw_s	4
	__stw	<__temp
	__ldwi	144
	  jsr	ltzp
	__lbeq	LL69
	__ldwi	_note_data
	__addw_s	6
	__pushw
	__ldw_s	6
	__stbps
	__ldw_s	6
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL71
	__ldb	_xpcm_sw
LL71:

	__boolw
	__tstw
	__lbeq	LL70
	__ldb	_ch_topbank
	  call	_chg_cbank
	  call	_pcm_off
	__ldw	_xpcmdata
	__pushw
	__ldw_s	6
	__pushw
	__ldwi	3
	  jsr	asl
	__addws
	__stw_s	0
	__stw	__ptr
	__ldwp	__ptr
	__stw	_xpcm_addr
	__ldw_s	0
	__addwi	2
	__stw	__ptr
	__ldwp	__ptr
	__stw	_xpcm_len
	__ldw_s	0
	__addwi	4
	__stw	__ptr
	__ldwp	__ptr
	  stx	_xpcm_bank
	__ldb	_xpcm_bank
	  call	_chg_pcmbank
	__ldw_s	6
	  call	_pcm_on
	__ldb	_ch_nowbank
	  call	_chg_cbank
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_ch_cnt
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	__ldw_s	6
	__pushw
	__ldwi	_ch_vol
	__addw_s	8
	__ldb_p
	  call	_set_vol
	__lbra	LL45
LL70:

	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldwi	_note_sw
	__addw_s	6
	__ldb_p
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL72
	__ldw_s	6
	__aslw
	__addwi	_note_envadr
	__pushw
	__ldwi	0
	__stwps
	__lbra	LL73
LL72:

	__ldw_s	6
	__aslw
	__addwi	_note_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	18
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_note_sw
	__addw_s	10
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
LL73:

	__ldwi	_pitch_sw
	__addw_s	6
	__ldb_p
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL74
	__ldw_s	6
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__ldwi	0
	__stwps
	__lbra	LL75
LL74:

	__ldw_s	6
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	8
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_pitch_sw
	__addw_s	10
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
LL75:

	__ldb	_ch_nowbank
	  call	_chg_cbank
	__ldw_s	6
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL77
	__ldwi	_noise_sw
	__pushw
	__ldw_s	8
	__subwi	4
	__addws
	__ldb_p
LL77:

	__boolw
	__tstw
	__lbeq	LL76
	__ldwi	_noise_freq
	__pushw
	__ldw_s	8
	__subwi	4
	__addws
	__pushw
	__ldw_s	6
	__andwi	31
	__stbps
	__ldwi	2055
	__stw	_bx
	__ldwi	128
	__pushw
	__ldw_s	6
	__andwi	31
	__orws
	  call	_poke.2
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_ch_cnt
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	__ldw_s	6
	__pushw
	__ldwi	_ch_vol
	__addw_s	8
	__ldb_p
	  call	_set_vol
	__lbra	LL45
LL76:

	__ldw_s	4
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	5
	__pushw
	__ldw_s	8
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__phb	1
	__ldwi	11
	  call	_put_hex.4
	__ldb	_ch_topbank
	  call	_chg_cbank
	__ldwi	_lfo_sw
	__addw_s	6
	__pushw
	__ldwi	0
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	6
	__pushw
	__ldwi	_sound_dat
	__addwi	12
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_num
	__addw_s	10
	__ldb_p
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldw_s	6
	__pushw
	__ldw_s	6
	  call	_set_note
	__ldb	_ch_nowbank
	  call	_chg_cbank
	__ldwi	_detune
	__addw_s	6
	__ldb_p
	__tstw
	__lbeq	LL78
	__ldwi	_detune
	__addw_s	6
	__ldb_p
	__andwi	128
	__tstw
	__lbeq	LL79
	__ldw_s	6
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_detune
	__addw_s	10
	__ldb_p
	__andwi	127
	__subws
	__stwps
	__lbra	LL80
LL79:

	__ldw_s	6
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_detune
	__addw_s	10
	__ldb_p
	__andwi	127
	__addws
	__stwps
LL80:

LL78:

	__ldwi	2051
	__stw	_bx
	__ldw_s	6
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	8
	  jsr	asr
	__andwi	15
	  call	_poke.2
	__ldwi	2050
	__stw	_bx
	__ldw_s	6
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__andwi	255
	  call	_poke.2
	incw	_seq_ptr
	__ldw	_seq_ptr
	__ldb_p
	__stw	_j
	__ldw	_seq_ptr
	incw	_seq_ptr
	__ldwi	_ch_cnt
	__addw_s	6
	__pushw
	__ldw	_j
	__stbps
	__ldw_s	6
	__pushw
	__ldwi	_ch_vol
	__addw_s	8
	__ldb_p
	  call	_set_vol
LL69:

LL45:

	__addmi	8,__stack
	  rts
	.endp

_seqproc:
	dw   SEQ_EC
	dw   SEQ_ED
	dw   SEQ_EE
	dw   SEQ_EF
	dw   SEQ_F0
	dw   SEQ_F1
	dw   SEQ_F2
	dw   endpoint ; f3
	dw   SEQ_F4
	dw   endpoint ; f5
	dw   endpoint ; f6
	dw   SEQ_F7   ; f7
	dw   SEQ_F8
	dw   SEQ_F9
	dw   SEQ_FA
	dw   SEQ_FB
	dw   SEQ_FC
	dw   SEQ_FD
	dw   SEQ_FE
	dw   SEQ_FF
	.proc _divxt
	__pushw
	__addmi	-4,__stack
	__stwi_s	0,0
	__stwi_s	0,2
LL82:

	__ldw_s	0
	__pushw
	__ldb_s	8
	  jsr	lt
	__lbne	LL84
	__lbra	LL85
LL83:

	__ldw_s	2
	__incw_s	2
	__lbra	LL82
LL84:

	__ldw_s	0
	__pushw
	__ldb_s	6
	__addws
	__stw_s	0
	__lbra	LL83
LL85:

	__ldw_s	2
	__lbra	LL81
LL81:

	__addmi	8,__stack
	  rts
	.endp

	.proc _drv_pitchenv
	__pushw
	__addmi	-1,__stack
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__stw	__ptr
	__ldwp	__ptr
	__tstw
	__lbeq	LL87
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	0
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__ldb_s	0
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL88
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	10
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_pitch_sw
	__addw_s	5
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	0
	__ldw_s	1
	__aslw
	__addwi	_pitch_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL88:

	__ldw_s	1
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL90
	__ldwi	_noise_sw
	__pushw
	__ldw_s	3
	__subwi	4
	__addws
	__ldb_p
LL90:

	__boolw
	__tstw
	__lbeq	LL89
	__ldb_s	0
	__andwi	128
	__tstw
	__lbeq	LL91
	__ldwi	_noise_freq
	__pushw
	__ldw_s	3
	__subwi	4
	__addws
	__pushw
	__ldb_p
	__pushw
	__ldb_s	4
	__andwi	127
	__subws
	__stbps
	__lbra	LL92
LL91:

	__ldwi	_noise_freq
	__pushw
	__ldw_s	3
	__subwi	4
	__addws
	__pushw
	__ldb_p
	__pushw
	__ldb_s	4
	__addws
	__stbps
LL92:

	__ldwi	2055
	__stw	_bx
	__ldwi	128
	__pushw
	__ldwi	_noise_freq
	__pushw
	__ldw_s	5
	__subwi	4
	__addws
	__ldb_p
	__andwi	31
	__orws
	  call	_poke.2
LL89:

	__ldb_s	0
	__andwi	128
	__tstw
	__lbeq	LL93
	__ldw_s	1
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldb_s	4
	__andwi	127
	__subws
	__stwps
	__lbra	LL94
LL93:

	__ldw_s	1
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldb_s	4
	__addws
	__stwps
LL94:

	__ldwi	2051
	__stw	_bx
	__ldw_s	1
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	8
	  jsr	asr
	__andwi	15
	  call	_poke.2
	__ldwi	2050
	__stw	_bx
	__ldw_s	1
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__andwi	255
	  call	_poke.2
LL87:

LL86:

	__addmi	3,__stack
	  rts
	.endp

	.proc _drv_lfoseq
	__pushw
	__addmi	-2,__stack
	__ldwi	_lfo_num
	__addw_s	2
	__ldb_p
	__stw	<__temp
	__ldwi	255
	  jsr	nezp
	__lbeq	LL96
	__ldwi	_sound_dat
	__addwi	12
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_num
	__addw_s	4
	__ldb_p
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__stw_s	0
	__ldwi	_lfo_lev
	__addw_s	2
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	5
	__pushw
	__ldw_s	4
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__phb	1
	__ldwi	15
	  call	_put_hex.4
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	5
	__pushw
	__ldw_s	4
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__phb	1
	__ldwi	16
	  call	_put_hex.4
	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	5
	__pushw
	__ldw_s	4
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__phb	1
	__ldwi	17
	  call	_put_hex.4
	__ldwi	LL97
	__pushw
	__ldwi	_lfo_sw
	__addw_s	4
	__ldb_p
	  jmp	___case
LL99:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL100
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL101
LL100:

	__ldwi	_lfo_sw
	__addw_s	2
	__pushw
	__ldwi	1
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__addwi	2
	__stw	__ptr
	__ldwp	__ptr
	  call	_divxt
	__stbps
	__ldwi	_lfo_stp
	__addw_s	2
	__pushw
	__ldwi	_lfo_ct2
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_lev
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	  call	_divxt
	__stbps
	__ldwi	_lfo_lev
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL102
	__ldwi	_lfo_lev
	__addw_s	2
	__pushw
	__ldwi	1
	__stbps
LL102:

LL101:

	__lbra	LL98
LL103:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL104
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL104:

	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL105
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL106
LL105:

	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_lev
	__addw_s	6
	__ldb_p
	__subws
	__stwps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldwi	_lfo_stp
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL107
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_sw
	__addw_s	2
	__pushw
	__ldwi	2
	__stbps
LL107:

LL106:

	__lbra	LL98
LL108:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL109
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL109:

	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL110
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL111
LL110:

	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_lev
	__addw_s	6
	__ldb_p
	__addws
	__stwps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldwi	_lfo_stp
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL112
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_sw
	__addw_s	2
	__pushw
	__ldwi	3
	__stbps
LL112:

LL111:

	__lbra	LL98
LL113:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL114
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL114:

	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL115
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL116
LL115:

	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_lev
	__addw_s	6
	__ldb_p
	__addws
	__stwps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldwi	_lfo_stp
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL117
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_sw
	__addw_s	2
	__pushw
	__ldwi	4
	__stbps
LL117:

LL116:

	__lbra	LL98
LL118:

	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL119
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL119:

	__ldwi	_lfo_ct2
	__addw_s	2
	__ldb_p
	__tstw
	__lbeq	LL120
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__lbra	LL121
LL120:

	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_lfo_lev
	__addw_s	6
	__ldb_p
	__subws
	__stwps
	__ldwi	_lfo_ct2
	__addw_s	2
	__pushw
	__ldwi	_lfo_stp
	__addw_s	4
	__ldb_p
	__stbps
	__ldwi	_lfo_cnt
	__addw_s	2
	__ldb_p
	__notw
	__tstw
	__lbeq	LL122
	__ldwi	_lfo_cnt
	__addw_s	2
	__pushw
	__ldw_s	2
	__addwi	1
	__stw	__ptr
	__ldwp	__ptr
	__stbps
	__ldwi	_lfo_sw
	__addw_s	2
	__pushw
	__ldwi	1
	__stbps
LL122:

LL121:

	__lbra	LL98
	__lbra	LL98
LL97:

	.dw	0,LL99,1,LL103,2,LL108,3,LL113
	.dw	4,LL118
	.dw	LL98,0
LL98:

	__ldwi	2051
	__stw	_bx
	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	8
	  jsr	asr
	__andwi	15
	  call	_poke.2
	__ldwi	2050
	__stw	_bx
	__ldw_s	2
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__andwi	255
	  call	_poke.2
LL96:

LL95:

	__addmi	4,__stack
	  rts
	.endp

	.proc _drv_intr
	__addmi	-7,__stack
	__stwi_s	0,5
LL124:

	__ldw_s	5
	__stw	<__temp
	__ldwi	6
	  jsr	ltzp
	__lbne	LL126
	__lbra	LL127
LL125:

	__ldw_s	5
	__incw_s	5
	__lbra	LL124
LL126:

	__ldw_s	5
	  stx	_reg_ch
	__ldwi	2048
	__stw	_bx
	__ldw_s	5
	  call	_poke.2
	__ldwi	_ch_cnt
	__addw_s	5
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	5
	__pushw
	__ldw_s	7
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__phb	1
	__ldwi	12
	  call	_put_hex.4
	__ldwi	_ch_cnt
	__addw_s	5
	__ldb_p
	__notw
	__tstw
	__lbeq	LL128
	__ldw_s	5
	__aslw
	__addwi	_seq_pos
	__stw	__ptr
	__ldwp	__ptr
	__stw	_seq_ptr
	__ldwi	_ch_bank
	__addw_s	5
	__ldb_p
	  stx	_ch_nowbank
	__ldb	_ch_nowbank
	  call	_chg_cbank
	__ldw_s	5
	__pushw
	__ldw	_seq_ptr
	__ldb_p
	  call	_seq
	__ldw_s	5
	__aslw
	__addwi	_seq_pos
	__pushw
	__ldw	_seq_ptr
	__stwps
	__ldwi	_ch_bank
	__addw_s	5
	__pushw
	__ldb	_ch_nowbank
	__stbps
	__ldb	_ch_topbank
	  call	_chg_cbank
LL128:

	__ldwi	_ch_cnt
	__addw_s	5
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
	__ldw_s	5
	__aslw
	__addwi	_volume_envadr
	__stw	__ptr
	__ldwp	__ptr
	__tstw
	__lbeq	LL129
	__ldw_s	5
	__aslw
	__addwi	_volume_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	2
	__ldw_s	5
	__aslw
	__addwi	_volume_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__ldb_s	2
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL130
	__ldwi	_ch_vol
	__addw_s	5
	__ldb_p
	__andwi	127
	__stb_s	2
	__ldw_s	5
	__aslw
	__addwi	_volume_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	6
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldb_s	6
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldw_s	5
	__aslw
	__addwi	_volume_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	2
	__ldw_s	5
	__aslw
	__addwi	_volume_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL130:

	__ldb_s	2
	__andwi	31
	  call	_mixvol
LL129:

	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__stw	__ptr
	__ldwp	__ptr
	__tstw
	__lbeq	LL131
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	2
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
	__ldb_s	2
	__stw	<__temp
	__ldwi	255
	  jsr	eqzp
	__lbeq	LL132
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__pushw
	__ldwi	_sound_dat
	__addwi	20
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	_note_sw
	__addw_s	9
	__ldb_p
	__pushw
	__ldwi	1
	  jsr	asl
	__addws
	__stw	__ptr
	__ldwp	__ptr
	__stwps
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__stw	__ptr
	__ldwp	__ptr
	__stw	__ptr
	__ldwp	__ptr
	__stb_s	2
	__ldw_s	5
	__aslw
	__addwi	_note_envadr
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL132:

	__ldb_s	2
	__andwi	128
	__tstw
	__lbeq	LL133
	__ldwi	_note_data
	__addw_s	5
	__ldb_p
	__stb_s	0
	__ldb_s	2
	__andwi	127
	__stb_s	1
	__pushw
	__ldwi	12
	  jsr	sdiv
	__pushw
	__ldwi	4
	  jsr	asl
	__stw_s	3
	__ldb_s	0
	__pushw
	__ldw_s	5
	__subws
	__stb_s	0
	__ldb_s	1
	__pushw
	__ldwi	12
	  jsr	smod
	__stw_s	3
	__ldb_s	0
	__andwi	15
	__pushw
	__ldw_s	5
	  jsr	ge
	__lbeq	LL134
	__ldb_s	0
	__pushw
	__ldw_s	5
	__subws
	__stb_s	0
	__lbra	LL135
LL134:

	__ldb_s	0
	__subwi	4
	__stb_s	0
	__pushw
	__ldw_s	5
	__subws
	__stb_s	0
LL135:

	__ldwi	_note_data
	__addw_s	5
	__pushw
	__ldb_s	2
	__stbps
	__lbra	LL136
LL133:

	__ldwi	_note_data
	__addw_s	5
	__ldb_p
	__stb_s	0
	__ldb_s	2
	__stb_s	1
	__pushw
	__ldwi	12
	  jsr	sdiv
	__pushw
	__ldwi	4
	  jsr	asl
	__stw_s	3
	__ldb_s	0
	__addw_s	3
	__stb_s	0
	__ldb_s	1
	__pushw
	__ldwi	12
	  jsr	smod
	__stw_s	3
	__ldb_s	0
	__addw_s	3
	__stb_s	0
	__andwi	15
	__stw	<__temp
	__ldwi	12
	  jsr	gezp
	__lbeq	LL137
	__ldb_s	0
	__addwi	4
	__stb_s	0
LL137:

	__ldwi	_note_data
	__addw_s	5
	__pushw
	__ldb_s	2
	__stbps
LL136:

	__ldwi	_note_data
	__addw_s	5
	__ldb_p
	__phw	4,4
	__ldwi	2
	__phb	2
	__ldwi	5
	__pushw
	__ldw_s	7
	__pushw
	__ldwi	2
	  jsr	asl
	__addws
	__phb	1
	__ldwi	11
	  call	_put_hex.4
	__ldw_s	5
	__pushw
	__ldwi	_note_data
	__addw_s	7
	__ldb_p
	  call	_set_note
	__ldwi	2051
	__stw	_bx
	__ldw_s	5
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	8
	  jsr	asr
	__andwi	15
	  call	_poke.2
	__ldwi	2050
	__stw	_bx
	__ldw_s	5
	__aslw
	__addwi	_seq_freq
	__stw	__ptr
	__ldwp	__ptr
	__andwi	255
	  call	_poke.2
LL131:

	__ldw_s	5
	  call	_drv_pitchenv
	__ldw_s	5
	  call	_drv_lfoseq
	__lbra	LL125
LL127:

LL123:

	__addmi	7,__stack
	  rts
	.endp

	.proc _main
	__addmi	-4,__stack
	__stwi_s	0,2
	  call	_disp_off
	  call	_cls
	__stwi_s	1,0
LL139:

	__ldw_s	0
	__stw	<__temp
	__ldwi	15
	  jsr	ltzp
	__lbne	LL141
	__lbra	LL142
LL140:

	__ldw_s	0
	__incw_s	0
	__lbra	LL139
LL141:

	__ldw_s	0
	__stw	_color_reg
	__ldwi	511
	__stw	_color_data
	__lbra	LL140
LL142:

	  call	_load_default_font
	  call	_disp_on
	__ldwi	LL0+0
	__phw	3,3
	__ldwi	5
	__phb	1
	__ldwi	5
	  call	_put_string.3
	  call	_drv_init
	__ldwi	LL0+25
	__phw	3,3
	__ldwi	5
	__phb	1
	__ldwi	6
	  call	_put_string.3
LL143:

	__ldwi	1
	__tstw
	__lbeq	LL144
	  ldy	#0
	  call	_vsync
	__lbra	LL143
LL144:

LL138:

	__addmi	4,__stack
	  rts
	.endp

	.data
	.bank CONST_BANK
	.org $4000
LL0:
	.db	73,78,73,84,73,65,76,73
	.db	90,69,83,32,72,117,83,73
	.db	67,32,68,82,73,86,69,82
	.db	0,79,75,0
_freq:
	.dw	4068
	.dw	3839
	.dw	3624
	.dw	3420
	.dw	3228
	.dw	3047
	.dw	2876
	.dw	2715
	.dw	2562
	.dw	2419
	.dw	2283
	.dw	2155
	.dw	2034
	.dw	1920
	.dw	1812
	.dw	1710

	.bss
_reg_ch:		.ds	1
_ch_cnt:		.ds	8
_ch_vol:		.ds	8
_ch_bank:		.ds	8
_ch_nowbank:		.ds	1
_ch_topbank:		.ds	1
_note_data:		.ds	8
_pitch_sw:		.ds	8
_note_sw:		.ds	8
_detune:		.ds	8
_panpod:		.ds	8
_loop_cnt:		.ds	8
_seq_ptr:		.ds	2
_seq_pos:		.ds	16
_seq_freq:		.ds	16
_pitch_envadr:		.ds	16
_volume_envadr:		.ds	16
_note_envadr:		.ds	16
_i:		.ds	2
_j:		.ds	2
_noise_freq:		.ds	2
_noise_sw:		.ds	2
_lfo_num:		.ds	8
_lfo_cnt:		.ds	8
_lfo_ct2:		.ds	8
_lfo_stp:		.ds	8
_lfo_lev:		.ds	8
_lfo_sw:		.ds	8
_xpcm_addr:		.ds	2
_xpcm_len:		.ds	2
_xpcm_bank:		.ds	1
_xpcm_mode:		.ds	1
_xpcm_sw:		.ds	1
_xpcm_sp:		.ds	1
__arg:

;0 error(s) in compilation
;	literal pool:28
;	constant pool:32
;	global pool:2496
;	Macro pool:1235
