; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.21, 2005/04/09, Denki release)
; on Tue Jan 24 18:43:56 2012
;

HUC	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.data
	.dw $0800
_image_chr:
	.incchr "image.pcx"
	.code
	.data
	.dw $0
_image_bat:
	.incbat "image.pcx",4096
	.code
	.data
	.dw $0
_image_pal:
	.incpal "image.pcx",0
	.code
	.proc _main
	__ldwi	0
	__stw	_j
	  call	_disp_off
	_load_background	_image_chr,_image_pal,_image_bat,#32,#28
	  call	_disp_on
	__ldwi	0
	__stw	_i
LL2:

	__ldw	_i
	__stw	<__temp
	__ldwi	16
	  jsr	ltzp
	__lbne	LL4
	__lbra	LL5
LL3:

	incw	_i
	__ldw	_i
	__lbra	LL2
LL4:

	__ldwi	_palette
	__addw	_i
	__pushw
	__ldw	_i
	__stw	_color_reg
	  call	_get_color.1
	__stbps
	__ldwi	_palette
	__pushw
	__ldw	_i
	__addwi	16
	__addws
	__pushw
	__ldwi	15
	__subw	_i
	__stw	_color_reg
	  call	_get_color.1
	__stbps
	__ldwi	_palette
	__pushw
	__ldw	_i
	__addwi	32
	__addws
	__pushw
	__ldw	_i
	__stw	_color_reg
	  call	_get_color.1
	__stbps
	__lbra	LL3
LL5:

LL6:

LL7:

LL8:

	__ldwi	0
	__stw	_i
LL10:

	__ldw	_i
	__stw	<__temp
	__ldwi	16
	  jsr	ltzp
	__lbne	LL12
	__lbra	LL13
LL11:

	incw	_i
	__ldw	_i
	__lbra	LL10
LL12:

	__ldw	_i
	__stw	_color_reg
	__ldwi	_palette
	__pushw
	__ldw	_i
	__addw	_j
	__addws
	__ldb_p
	__stw	_color_data
	__lbra	LL11
LL13:

	incw	_j
	__ldw	_j
	__stw	<__temp
	__ldwi	32
	  jsr	eqzp
	__lbeq	LL14
	__ldwi	0
	__stw	_j
LL14:

	__ldwi	1
	  ldy	#1
	  call	_vsync
	__lbra	LL8
LL9:

LL1:

	  rts
	.endp


	.bss
_i:		.ds	2
_j:		.ds	2
_palette:		.ds	48
__arg:

;0 error(s) in compilation
;	literal pool:0
;	constant pool:0
;	global pool:576
;	Macro pool:1065
