; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.21, 2005/04/09, Denki release)
; on Fri Jan 27 23:19:41 2012
;

HUC	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.proc _dispscore
	__pushw
	__addmi	-2,__stack
	__ldw_s	4
	__pushw
	__ldwi	10
	  jsr	sdiv
	__stw_s	0
	__ldwi	5
	  call	_spr_set
	__ldwi	29312
	__pushw
	__ldwi	64
	__pushw
	__ldw_s	8
	__pushw
	__ldwi	10
	__pushw
	__ldw_s	8
	  jsr	smul
	__subws
	  jsr	smul
	__addws
	  call	_spr_pattern
	__ldw_s	0
	__stw_s	4
	__pushw
	__ldwi	10
	  jsr	sdiv
	__stw_s	0
	__ldwi	4
	  call	_spr_set
	__ldwi	29312
	__pushw
	__ldwi	64
	__pushw
	__ldw_s	8
	__pushw
	__ldwi	10
	__pushw
	__ldw_s	8
	  jsr	smul
	__subws
	  jsr	smul
	__addws
	  call	_spr_pattern
	__ldw_s	0
	__stw_s	4
	__pushw
	__ldwi	10
	  jsr	sdiv
	__stw_s	0
	__ldwi	3
	  call	_spr_set
	__ldwi	29312
	__pushw
	__ldwi	64
	__pushw
	__ldw_s	8
	__pushw
	__ldwi	10
	__pushw
	__ldw_s	8
	  jsr	smul
	__subws
	  jsr	smul
	__addws
	  call	_spr_pattern
	__ldw_s	2
	__pushw
	__ldwi	10
	  jsr	sdiv
	__stw_s	0
	__ldwi	8
	  call	_spr_set
	__ldwi	29312
	__pushw
	__ldwi	64
	__pushw
	__ldw_s	6
	__pushw
	__ldwi	10
	__pushw
	__ldw_s	8
	  jsr	smul
	__subws
	  jsr	smul
	__addws
	  call	_spr_pattern
	__ldw_s	0
	__stw_s	2
	__pushw
	__ldwi	10
	  jsr	sdiv
	__stw_s	0
	__ldwi	7
	  call	_spr_set
	__ldwi	29312
	__pushw
	__ldwi	64
	__pushw
	__ldw_s	6
	__pushw
	__ldwi	10
	__pushw
	__ldw_s	8
	  jsr	smul
	__subws
	  jsr	smul
	__addws
	  call	_spr_pattern
	__ldw_s	0
	__stw_s	2
	__pushw
	__ldwi	10
	  jsr	sdiv
	__stw_s	0
	__ldwi	6
	  call	_spr_set
	__ldwi	29312
	__pushw
	__ldwi	64
	__pushw
	__ldw_s	6
	__pushw
	__ldwi	10
	__pushw
	__ldw_s	8
	  jsr	smul
	__subws
	  jsr	smul
	__addws
	  call	_spr_pattern
LL1:

	__addmi	6,__stack
	  rts
	.endp

	.proc _init_score
	__pushw
	__addmi	-2,__stack
	__ldw_s	4
	__stw_s	0
LL3:

	__ldw_s	0
	__pushw
	__ldw_s	6
	__addwi	3
	  jsr	lt
	__lbne	LL5
	__lbra	LL6
LL4:

	__ldw_s	0
	__incw_s	0
	__lbra	LL3
LL5:

	__ldw_s	0
	  call	_spr_set
	__ldwi	80
	__pushw
	__ldw_s	2
	__pushw
	__ldw_s	8
	__subws
	__pushw
	__ldwi	16
	  jsr	smul
	__addws
	  call	_spr_x
	__ldwi	72
	  call	_spr_y
	__ldwi	29312
	  call	_spr_pattern
	__ldwi	185
	  stx	_al
	__ldwi	0
	  call	_spr_ctrl.2
	__ldwi	3
	  call	_spr_pal
	__ldwi	1
	  call	_spr_pri
	__lbra	LL4
LL6:

LL7:

	__ldw_s	0
	__pushw
	__ldw_s	4
	  jsr	le
	__lbne	LL9
	__lbra	LL10
LL8:

	__ldw_s	0
	__incw_s	0
	__lbra	LL7
LL9:

	__ldw_s	0
	  call	_spr_set
	__ldwi	130
	__pushw
	__ldw_s	2
	__pushw
	__ldw_s	8
	__subws
	__pushw
	__ldwi	16
	  jsr	smul
	__addws
	  call	_spr_x
	__ldwi	72
	  call	_spr_y
	__ldwi	29312
	  call	_spr_pattern
	__ldwi	185
	  stx	_al
	__ldwi	0
	  call	_spr_ctrl.2
	__ldwi	3
	  call	_spr_pal
	__ldwi	1
	  call	_spr_pri
	__lbra	LL8
LL10:

LL2:

	__addmi	6,__stack
	  rts
	.endp

	.proc _main
	__addmi	-16,__stack
	__stwi_s	0,4
	__stwi_s	0,2
	__stwi_s	100,12
	__stwi_s	100,14
	__stwi_s	150,10
	__stwi_s	150,8
	load_sprites	#28672,_racket_left,#1
	load_sprites	#28928,_racket_right,#1
	load_sprites	#29184,_ball,#1
	load_sprites	#29312,_digits,#2
	  call	_init_satb
	__ldwi	0
	  call	_spr_set
	__ldwi	33
	  call	_spr_x
	__ldw_s	12
	  call	_spr_y
	__ldwi	28672
	  call	_spr_pattern
	__ldwi	185
	  stx	_al
	__ldwi	16
	  call	_spr_ctrl.2
	__ldwi	0
	  call	_spr_pal
	__ldwi	1
	  call	_spr_pri
	__ldwi	1
	  call	_spr_set
	__ldwi	240
	  call	_spr_x
	__ldw_s	14
	  call	_spr_y
	__ldwi	28928
	  call	_spr_pattern
	__ldwi	185
	  stx	_al
	__ldwi	16
	  call	_spr_ctrl.2
	__ldwi	1
	  call	_spr_pal
	__ldwi	1
	  call	_spr_pri
	__ldwi	2
	  call	_spr_set
	__ldwi	150
	  call	_spr_x
	__ldwi	150
	  call	_spr_y
	__ldwi	29184
	  call	_spr_pattern
	__ldwi	185
	  stx	_al
	__ldwi	0
	  call	_spr_ctrl.2
	__ldwi	2
	  call	_spr_pal
	__ldwi	1
	  call	_spr_pri
	__ldwi	3
	__pushw
	__ldwi	8
	  call	_init_score
	_load_background	_special_bg,_special_pal,_special_bat,#32,#28
	__ldwi	1
	  ldy	#1
	  call	_vsync
	_set_sprpal	#0,_racket_left_colors,#1
	_set_sprpal	#1,_racket_right_colors,#1
	_set_sprpal	#2,_ball_colors,#1
	_set_sprpal	#3,_digits_colors,#1
	__stwi_s	0,0
LL12:

LL13:

LL14:

	__ldw_s	0
	__incw_s	0
	__ldwi	1
	  ldy	#1
	  call	_vsync
	__ldwi	0
	  call	_spr_set
	__ldw_s	12
	  call	_spr_y
	__ldwi	1
	  call	_spr_set
	__ldw_s	14
	  call	_spr_y
	__ldwi	2
	  call	_spr_set
	__ldw_s	0
	__pushw
	__ldwi	200
	  jsr	smod
	  call	_spr_x
	__ldw_s	0
	__pushw
	__ldwi	200
	  jsr	smod
	  call	_spr_y
	__ldw_s	4
	__pushw
	__ldw_s	4
	  call	_dispscore
	  ldy	#0
	  call	_satb_update
	__lbra	LL14
LL15:

LL11:

	__addmi	16,__stack
	  rts
	.endp

	.data
	.dw $0
_racket_left:
	.incspr "racketleft.pcx",0,0,2,2
	.code
	.data
	.dw $0
_racket_left_colors:
	.incpal "racketleft.pcx",0,1
	.code
	.data
	.dw $0
_racket_right:
	.incspr "racketright.pcx",0,0,2,2
	.code
	.data
	.dw $0
_racket_right_colors:
	.incpal "racketright.pcx",0,1
	.code
	.data
	.dw $0
_ball:
	.incspr "ball.pcx",0,0,1,1
	.code
	.data
	.dw $0
_ball_colors:
	.incpal "ball.pcx",0,1
	.code
	.data
	.dw $0
_digits:
	.incspr "digits.pcx",0,0,1,1
	.code
	.data
	.dw $0
_digits1:
	.incspr "digits.pcx",16,0,1,1
	.code
	.data
	.dw $0
_digits2:
	.incspr "digits.pcx",32,0,1,1
	.code
	.data
	.dw $0
_digits3:
	.incspr "digits.pcx",0,16,1,1
	.code
	.data
	.dw $0
_digits4:
	.incspr "digits.pcx",16,16,1,1
	.code
	.data
	.dw $0
_digits5:
	.incspr "digits.pcx",32,16,1,1
	.code
	.data
	.dw $0
_digits6:
	.incspr "digits.pcx",0,32,1,1
	.code
	.data
	.dw $0
_digits7:
	.incspr "digits.pcx",16,32,1,1
	.code
	.data
	.dw $0
_digits8:
	.incspr "digits.pcx",32,32,1,1
	.code
	.data
	.dw $0
_digits9:
	.incspr "digits.pcx",0,48,1,1
	.code
	.data
	.dw $0
_digits10:
	.incspr "digits.pcx",16,48,1,1
	.code
	.data
	.dw $0
_digits11:
	.incspr "digits.pcx",32,48,1,1
	.code
	.data
	.dw $0
_digits_colors:
	.incpal "digits.pcx",0,1
	.code
	.data
	.dw $0800
_special_bg:
	.incchr "special.pcx",32,28
	.code
	.data
	.dw $0
_special_pal:
	.incpal "special.pcx"
	.code
	.data
	.dw $0
_special_bat:
	.incbat "special.pcx",4096,32,28
	.code

	.bss
__arg:

;0 error(s) in compilation
;	literal pool:0
;	constant pool:0
;	global pool:1376
;	Macro pool:1249
