; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.21, 2005/04/09, Denki release)
; on Tue Jan 24 18:48:04 2012
;

HUC	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.proc _strcpy
	__pushw
LL2:

	__ldw_s	0
	__ldb_p
	__tstw
	__lbeq	LL3
	__ldw_s	2
	__incw_s	2
	__pushw
	__ldw_s	2
	__incw_s	2
	__ldb_p
	__stbps
	__lbra	LL2
LL3:

	__ldw_s	2
	__pushw
	__ldwi	0
	__stbps
LL1:

	__addmi	4,__stack
	  rts
	.endp

	.proc _main
	__addmi	-1,__stack
	__ldwi	50
	  stx	_DexP1
	__ldwi	70
	  stx	_AtkP1
	__ldwi	60
	  stx	_DefP1
	__ldwi	_NamP1
	__stw	_di
	__ldwi	LL0+0
	__stw	_si
	  call	_strcpy.2
LL5:

	__ldwi	1
	__tstw
	__lbeq	LL6
	  call	_cls
	__ldwi	1
	  stx	_al
	__ldwi	2
	  call	_set_font_color.2
	  call	_load_default_font
	__stbi_s	0,0
	_load_background	_titlegfx,_titlepal,_titlebat,#32,#28
	__ldwi	LL0+6
	__phw	3,3
	__ldwi	11
	__phb	1
	__ldwi	18
	  call	_put_string.3
	__ldwi	LL0+21
	__phw	3,3
	__ldwi	11
	__phb	1
	__ldwi	20
	  call	_put_string.3
	__ldwi	LL0+33
	__phw	3,3
	__ldwi	11
	__phb	1
	__ldwi	22
	  call	_put_string.3
	__ldwi	45
	__phb	2,2
	__ldwi	9
	__phb	1
	__ldwi	18
	  call	_put_char.3
LL7:

	__ldwi	0
	  call	_joytrg
	__andwi	8
	__notw
	__tstw
	__lbeq	LL8
	__ldwi	0
	  call	_joytrg
	__andwi	16
	__tstw
	__lbeq	LL10
	__ldb_s	0
	__stw	<__temp
	__ldwi	0
	  jsr	gtzp
LL10:

	__boolw
	__tstw
	__lbeq	LL9
	__ldb_s	0
	__subwi	1
	__stb_s	0
	__addwi	1
	__ldwi	32
	__phb	2,2
	__ldwi	9
	__phb	1
	__ldwi	20
	__pushw
	__ldwi	2
	__pushw
	__ldb_s	4
	  jsr	smul
	__addws
	  call	_put_char.3
	__ldwi	45
	__phb	2,2
	__ldwi	9
	__phb	1
	__ldwi	18
	__pushw
	__ldwi	2
	__pushw
	__ldb_s	4
	  jsr	smul
	__addws
	  call	_put_char.3
LL9:

	__ldwi	0
	  call	_joytrg
	__andwi	64
	__tstw
	__lbeq	LL12
	__ldb_s	0
	__stw	<__temp
	__ldwi	2
	  jsr	ltzp
LL12:

	__boolw
	__tstw
	__lbeq	LL11
	__ldb_s	0
	__addwi	1
	__stb_s	0
	__subwi	1
	__ldwi	32
	__phb	2,2
	__ldwi	9
	__phb	1
	__ldwi	16
	__pushw
	__ldwi	2
	__pushw
	__ldb_s	4
	  jsr	smul
	__addws
	  call	_put_char.3
	__ldwi	45
	__phb	2,2
	__ldwi	9
	__phb	1
	__ldwi	18
	__pushw
	__ldwi	2
	__pushw
	__ldb_s	4
	  jsr	smul
	__addws
	  call	_put_char.3
LL11:

	__ldwi	1
	  ldy	#1
	  call	_vsync
	__lbra	LL7
LL8:

	__ldwi	LL13
	__pushw
	__ldb_s	2
	  jmp	___case
LL15:

	__ldwi	500
	__pushw
	__ldwi	50
	__pushw
	__ldwi	50
	__pushw
	__ldwi	30
	  call	_battle
	__lbra	LL14
LL16:

	__ldwi	_Entry
	__stw	_di
	__ldwi	LL0+44
	__stw	_si
	  call	_strcpy.2
	  call	_enter
	__ldwi	_NamP1
	__stw	_di
	__ldwi	_Entry
	__stw	_si
	  call	_strcpy.2
	__lbra	LL14
LL17:

	  call	_sprite
	__lbra	LL14
	__lbra	LL14
LL13:

	.dw	0,LL15,1,LL16,2,LL17
	.dw	LL14,0
LL14:

	__lbra	LL5
LL6:

LL4:

	__addmi	1,__stack
	  rts
	.endp

	.proc _battle
	__pushw
	__addmi	-16,__stack
	__ldwi	1
	  stx	_al
	__ldwi	2
	  call	_set_font_color.2
	  call	_load_default_font
LL19:

	__ldwi	1
	__tstw
	__lbeq	LL20
	  ldy	#0
	  call	_satb_update
	  call	_cls
	  call	_battlescreen
	__stwi_s	500,14
	__ldw_s	22
	__stw_s	12
	__stbi_s	1,1
	__stbi_s	1,0
LL21:

	__ldw_s	14
	__stw	<__temp
	__ldwi	0
	  jsr	gtzp
	__pushw
	__ldw_s	14
	__stw	<__temp
	__ldwi	0
	  jsr	gtzp
	__andws
	__tstw
	__lbeq	LL22
	__ldwi	_NamP1
	__phw	3,3
	__ldwi	17
	__phb	1
	__ldwi	23
	  call	_put_string.3
	__ldwi	LL0+50
	__phw	3,3
	__ldwi	17
	__phb	1
	__ldwi	24
	  call	_put_string.3
	__ldwi	LL0+57
	__phw	3,3
	__ldwi	8
	__phb	1
	__ldwi	16
	  call	_put_string.3
LL23:

	__ldwi	0
	  call	_joytrg
	__andwi	8
	__notw
	__tstw
	__lbeq	LL24
	  call	_rand
	__lbra	LL23
LL24:

	  call	_rand
	__pushw
	__ldwi	3
	  jsr	smod
	  ldy	#1
	  call	_vsync
	  call	_cls
	  call	_battlescreen
	__ldb_s	1
	__tstw
	__lbeq	LL25
	__pea_s	2
	__ldwi	2
	__pushw
	  call	_rand
	__pushw
	__ldb	_DexP1
	  jsr	smod
	  jsr	smul
	__pushw
	  call	_rand
	__pushw
	__ldb_s	22
	  jsr	smod
	__subws
	__stwps
	__ldw_s	2
	__stw	<__temp
	__ldwi	0
	  jsr	ltzp
	__lbeq	LL26
	__ldwi	LL0+68
	__phw	3,3
	__ldwi	5
	__phb	1
	__ldwi	1
	  call	_put_string.3
	__lbra	LL27
LL26:

	__pea_s	4
	__ldwi	2
	__pushw
	  call	_rand
	__pushw
	__ldb	_AtkP1
	  jsr	smod
	  jsr	smul
	__pushw
	  call	_rand
	__pushw
	__ldb_s	24
	  jsr	smod
	__subws
	__stwps
	__ldwi	LL0+79
	__phw	3,3
	__ldwi	5
	__phb	1
	__ldwi	1
	  call	_put_string.3
	__ldw_s	4
	__stw	<__temp
	__ldwi	0
	  jsr	ltzp
	__lbeq	LL28
	__ldw_s	12
	__subwi	1
	__stw_s	12
	__ldwi	1
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldwi	16
	__phb	1
	__ldwi	1
	  call	_put_number.4
	__lbra	LL29
LL28:

	__ldw_s	12
	__pushw
	__ldw_s	6
	__subws
	__stw_s	12
	__ldw_s	4
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldwi	16
	__phb	1
	__ldwi	1
	  call	_put_number.4
LL29:

	__ldwi	LL0+91
	__phw	3,3
	__ldwi	21
	__phb	1
	__ldwi	1
	  call	_put_string.3
LL27:

	__stbi_s	0,1
	__lbra	LL30
LL25:

	__pea_s	2
	__ldwi	2
	__pushw
	  call	_rand
	__pushw
	__ldb_s	22
	  jsr	smod
	  jsr	smul
	__pushw
	  call	_rand
	__pushw
	__ldb	_DexP1
	  jsr	smod
	__subws
	__stwps
	__ldw_s	2
	__stw	<__temp
	__ldwi	0
	  jsr	ltzp
	__lbeq	LL31
	__ldwi	LL0+98
	__phw	3,3
	__ldwi	5
	__phb	1
	__ldwi	1
	  call	_put_string.3
	__lbra	LL32
LL31:

	__pea_s	4
	__ldwi	2
	__pushw
	  call	_rand
	__pushw
	__ldb_s	26
	  jsr	smod
	  jsr	smul
	__pushw
	  call	_rand
	__pushw
	__ldb	_DefP1
	  jsr	smod
	__subws
	__stwps
	__ldwi	LL0+108
	__phw	3,3
	__ldwi	5
	__phb	1
	__ldwi	1
	  call	_put_string.3
	__ldw_s	4
	__stw	<__temp
	__ldwi	0
	  jsr	ltzp
	__lbeq	LL33
	__ldw_s	14
	__subwi	1
	__stw_s	14
	__ldwi	1
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldwi	15
	__phb	1
	__ldwi	1
	  call	_put_number.4
	__lbra	LL34
LL33:

	__ldw_s	14
	__pushw
	__ldw_s	6
	__subws
	__stw_s	14
	__ldw_s	4
	__phw	4,4
	__ldwi	4
	__phb	2
	__ldwi	15
	__phb	1
	__ldwi	1
	  call	_put_number.4
LL34:

	__ldwi	LL0+119
	__phw	3,3
	__ldwi	20
	__phb	1
	__ldwi	1
	  call	_put_string.3
LL32:

	__stbi_s	1,1
LL30:

	__ldw_s	14
	__phw	4,4
	__ldwi	5
	__phb	2
	__ldwi	25
	__phb	1
	__ldwi	23
	  call	_put_number.4
	__ldw_s	12
	__phw	4,4
	__ldwi	5
	__phb	2
	__ldwi	25
	__phb	1
	__ldwi	24
	  call	_put_number.4
	__ldwi	2
	  ldy	#1
	  call	_vsync
	__lbra	LL21
LL22:

	__ldw_s	14
	__stw	<__temp
	__ldwi	0
	  jsr	gtzp
	__lbeq	LL35
	__ldwi	LL0+126
	__phw	3,3
	__ldwi	8
	__phb	1
	__ldwi	8
	  call	_put_string.3
	__lbra	LL18
	__lbra	LL36
LL35:

	__ldwi	LL0+134
	__phw	3,3
	__ldwi	8
	__phb	1
	__ldwi	8
	  call	_put_string.3
	__ldwi	LL0+143
	__phw	3,3
	__ldwi	7
	__phb	1
	__ldwi	10
	  call	_put_string.3
	__ldwi	89
	__phb	2,2
	__ldwi	8
	__phb	1
	__ldwi	13
	  call	_put_char.3
	__ldwi	60
	  ldy	#1
	  call	_vsync
LL37:

	__ldwi	0
	  call	_joytrg
	__andwi	8
	__notw
	__tstw
	__lbeq	LL38
	__ldwi	0
	  call	_joytrg
	__andwi	247
	__tstw
	__lbeq	LL39
	__ldb_s	0
	__tstw
	__lbeq	LL40
	__ldb_s	0
	__subwi	1
	__stb_s	0
	__addwi	1
	__ldwi	78
	__phb	2,2
	__ldwi	8
	__phb	1
	__ldwi	13
	  call	_put_char.3
	__lbra	LL41
LL40:

	__ldb_s	0
	__addwi	1
	__stb_s	0
	__subwi	1
	__ldwi	89
	__phb	2,2
	__ldwi	8
	__phb	1
	__ldwi	13
	  call	_put_char.3
LL41:

LL39:

	  ldy	#0
	  call	_vsync
	__lbra	LL37
LL38:

	__ldb_s	0
	__notw
	__tstw
	__lbeq	LL42
	__lbra	LL18
LL42:

LL36:

	__lbra	LL19
LL20:

LL18:

	__addmi	24,__stack
	  rts
	.endp

	.proc _battlescreen
	__addmi	-2,__stack
	  call	_cls
	load_sprites	#4096,_screengfx,#1
	_set_bgpal	#0,_screenpal,#1
	__stbi_s	0,1
LL44:

	__ldb_s	1
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbeq	LL45
	__stbi_s	3,0
LL46:

	__ldb_s	0
	__stw	<__temp
	__ldwi	22
	  jsr	ltzp
	__lbeq	LL47
	__ldwi	260
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldb_s	0
	__addwi	1
	__stb_s	0
	__subwi	1
	__lbra	LL46
LL47:

	__ldwi	257
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	263
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	2
	  call	_put_raw.3
	__ldwi	257
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	22
	  call	_put_raw.3
	__ldwi	263
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldb_s	1
	__addwi	1
	__stb_s	1
	__subwi	1
	__lbra	LL44
LL45:

	__ldwi	256
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	258
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	262
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	2
	  call	_put_raw.3
	__ldwi	264
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	2
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	1
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	1
	  call	_put_raw.3
	__ldwi	256
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	22
	  call	_put_raw.3
	__ldwi	258
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	22
	  call	_put_raw.3
	__ldwi	262
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldwi	264
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	23
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	23
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	24
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	24
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	25
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	25
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	26
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	26
	  call	_put_raw.3
LL43:

	__addmi	2,__stack
	  rts
	.endp

	.proc _enter
	__addmi	-1,__stack
	__stbi_s	0,0
	  call	_cls
	  call	_load_default_font
	__ldwi	1
	  stx	_al
	__ldwi	2
	  call	_set_font_color.2
LL49:

	__ldwi	0
	  call	_joytrg
	__andwi	8
	__notw
	__tstw
	__lbeq	LL50
	__ldwi	0
	  call	_joytrg
	__andwi	128
	__tstw
	__lbeq	LL52
	__ldb_s	0
	__stw	<__temp
	__ldwi	0
	  jsr	gtzp
LL52:

	__boolw
	__tstw
	__lbeq	LL51
	__ldb_s	0
	__subwi	1
	__stb_s	0
	__addwi	1
LL51:

	__ldwi	0
	  call	_joytrg
	__andwi	32
	__tstw
	__lbeq	LL54
	__ldb_s	0
	__stw	<__temp
	__ldwi	4
	  jsr	ltzp
LL54:

	__boolw
	__tstw
	__lbeq	LL53
	__ldb_s	0
	__addwi	1
	__stb_s	0
	__subwi	1
LL53:

	__ldwi	0
	  call	_joytrg
	__andwi	16
	__tstw
	__lbeq	LL55
	__ldwi	_Entry
	__pushw
	__ldb_s	2
	__addws
	__pushw
	__ldb_p
	__addwi	1
	__stbps
	__subwi	1
LL55:

	__ldwi	0
	  call	_joytrg
	__andwi	64
	__tstw
	__lbeq	LL56
	__ldwi	_Entry
	__pushw
	__ldb_s	2
	__addws
	__pushw
	__ldb_p
	__subwi	1
	__stbps
	__addwi	1
LL56:

	__ldwi	_Entry
	__phw	3,3
	__ldwi	15
	__phb	1
	__ldwi	15
	  call	_put_string.3
	__ldwi	LL0+155
	__phw	3,3
	__ldwi	15
	__phb	1
	__ldwi	17
	  call	_put_string.3
	__ldwi	73
	__phb	2,2
	__ldwi	15
	__pushw
	__ldb_s	2
	__addws
	__phb	1
	__ldwi	17
	  call	_put_char.3
	__ldwi	1
	  ldy	#1
	  call	_vsync
	__lbra	LL49
LL50:

	__lbra	LL48
LL48:

	__addmi	1,__stack
	  rts
	.endp

	.proc _sprite
	__addmi	-4,__stack
	__stwi_s	1,2
	__ldwi	16
	__stw	_spriteX
	__ldwi	16
	__stw	_spriteY
	  call	_init_satb
	load_sprites	#16384,_sprgfx,#1
	__ldwi	0
	  call	_spr_set
	__ldwi	1
	  call	_spr_pri
	_set_sprpal	#0,_sprpal,#1
	__ldwi	16384
	  call	_spr_pattern
	__ldwi	185
	  stx	_al
	__ldwi	0
	  call	_spr_ctrl.2
	__ldwi	0
	  call	_spr_pal
	__ldw	_spriteX
	  call	_spr_x
	__ldw	_spriteY
	  call	_spr_y
LL58:

	__ldwi	1
	__tstw
	__lbeq	LL59
	__ldwi	LL60
	__pushw
	__ldw_s	4
	  jmp	___case
LL62:

	  ldy	#0
	  call	_spr_hide
	  call	_menu
	  ldy	#0
	  call	_spr_show
	__ldw_s	0
	__stw_s	2
	load_sprites	#16384,_sprgfx,#1
	__lbra	LL61
LL63:

	__stwi_s	1,0
	__pea_s	2
	  call	_move1
	__stwps
	__lbra	LL61
LL64:

	__stwi_s	2,0
	__pea_s	2
	  call	_move2
	__stwps
	__lbra	LL61
LL65:

	__stwi_s	3,0
	__pea_s	2
	  call	_move3
	__stwps
	__lbra	LL61
	__lbra	LL61
LL60:

	.dw	-1,LL62,1,LL63,2,LL64,3,LL65
	.dw	LL61,0
LL61:

	__lbra	LL58
LL59:

LL57:

	__addmi	4,__stack
	  rts
	.endp

	.proc _menu
	__addmi	-1,__stack
	  ldy	#0
	  call	_satb_update
	  call	_cls
	_set_bgpal	#0,_screenpal,#1
	__ldwi	1
	  stx	_al
	__ldwi	2
	  call	_set_font_color.2
	  call	_load_default_font
	load_sprites	#4096,_screengfx,#1
	__ldwi	256
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	258
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	262
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldwi	264
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__stbi_s	1,0
LL67:

	__ldb_s	0
	__stw	<__temp
	__ldwi	31
	  jsr	ltzp
	__lbeq	LL68
	__ldwi	257
	__phw	3,3
	__ldb_s	0
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	263
	__phw	3,3
	__ldb_s	0
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldb_s	0
	__addwi	1
	__stb_s	0
	__subwi	1
	__lbra	LL67
LL68:

	__stbi_s	1,0
LL69:

	__ldb_s	0
	__stw	<__temp
	__ldwi	27
	  jsr	ltzp
	__lbeq	LL70
	__ldwi	259
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	23
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldb_s	0
	__addwi	1
	__stb_s	0
	__subwi	1
	__lbra	LL69
LL70:

	__ldwi	256
	__phw	3,3
	__ldwi	23
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	262
	__phw	3,3
	__ldwi	23
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldwi	LL0+161
	__phw	3,3
	__ldwi	24
	__phb	1
	__ldwi	2
	  call	_put_string.3
	__ldwi	LL0+166
	__phw	3,3
	__ldwi	24
	__phb	1
	__ldwi	4
	  call	_put_string.3
	__ldwi	LL0+172
	__phw	3,3
	__ldwi	24
	__phb	1
	__ldwi	6
	  call	_put_string.3
	__ldwi	LL0+178
	__phw	3,3
	__ldwi	24
	__phb	1
	__ldwi	8
	  call	_put_string.3
	  ldy	#0
	  call	_vsync
LL71:

	__ldwi	0
	  call	_joytrg
	__notw
	__tstw
	__lbeq	LL72
	__lbra	LL71
LL72:

LL66:

	__addmi	1,__stack
	  rts
	.endp

	.proc _move1
	  call	_map1
LL74:

	__ldwi	8
	__pushw
	__ldwi	0
	  call	_joytrg
	__andws
	__notw
	__tstw
	__lbeq	LL75
	  ldy	#0
	  call	_satb_update
	__ldwi	0
	  call	_joy
	__andwi	128
	__tstw
	__lbeq	LL77
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	16
	  jsr	gtzp
LL77:

	__boolw
	__tstw
	__lbeq	LL76
	__ldw	_spriteX
	__subwi	1
	__stw	_spriteX
	__addwi	1
	__ldw	_spriteX
	  call	_spr_x
LL76:

	__ldwi	0
	  call	_joy
	__andwi	32
	__tstw
	__lbeq	LL79
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	224
	  jsr	ltzp
LL79:

	__boolw
	__tstw
	__lbeq	LL78
	__ldw	_spriteX
	incw	_spriteX
	__ldw	_spriteX
	  call	_spr_x
LL78:

	__ldwi	0
	  call	_joy
	__andwi	16
	__tstw
	__lbeq	LL81
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	16
	  jsr	gtzp
LL81:

	__boolw
	__tstw
	__lbeq	LL82
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	225
	  jsr	ltzp
LL82:

	__boolw
	__tstw
	__lbeq	LL80
	__ldw	_spriteY
	__subwi	1
	__stw	_spriteY
	__addwi	1
	__ldw	_spriteY
	  call	_spr_y
LL80:

	__ldwi	0
	  call	_joy
	__andwi	64
	__tstw
	__lbeq	LL84
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	192
	  jsr	ltzp
LL84:

	__boolw
	__tstw
	__lbeq	LL85
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	225
	  jsr	ltzp
LL85:

	__boolw
	__tstw
	__lbeq	LL83
	__ldw	_spriteY
	incw	_spriteY
	__ldw	_spriteY
	  call	_spr_y
LL83:

	__ldwi	0
	  call	_joy
	__andwi	32
	__tstw
	__lbeq	LL87
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	223
	  jsr	gtzp
LL87:

	__boolw
	__tstw
	__lbeq	LL88
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	242
	  jsr	ltzp
LL88:

	__boolw
	__tstw
	__lbeq	LL89
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	62
	  jsr	gtzp
LL89:

	__boolw
	__tstw
	__lbeq	LL90
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	66
	  jsr	ltzp
LL90:

	__boolw
	__tstw
	__lbeq	LL86
	__ldw	_spriteX
	incw	_spriteX
	__ldw	_spriteX
	  call	_spr_x
LL86:

	__ldw	_spriteX
	__stw	<__temp
	__ldwi	96
	  jsr	ltzp
	__lbeq	LL92
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	64
	  jsr	gtzp
LL92:

	__boolw
	__tstw
	__lbeq	LL93
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	144
	  jsr	ltzp
LL93:

	__boolw
	__tstw
	__lbeq	LL94
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	112
	  jsr	gtzp
LL94:

	__boolw
	__tstw
	__lbeq	LL91
	  ldy	#0
	  call	_spr_hide
	__ldwi	500
	__pushw
	__ldwi	2
	  jsr	smul
	__pushw
	__ldwi	3
	  jsr	sdiv
	__pushw
	  call	_rand
	__pushw
	__ldwi	500
	__pushw
	__ldwi	3
	  jsr	sdiv
	  jsr	smod
	__addws
	__pushw
	__ldwi	50
	__pushw
	__ldwi	50
	__pushw
	__ldwi	30
	  call	_battle
	__ldwi	16
	__stw	_spriteX
	__ldwi	16
	__stw	_spriteY
	__ldw	_spriteX
	  call	_spr_x
	__ldw	_spriteY
	  call	_spr_y
	  call	_map1
	  ldy	#0
	  call	_spr_show
	  ldy	#0
	  call	_satb_update
LL91:

	__ldw	_spriteX
	__stw	<__temp
	__ldwi	240
	  jsr	gtzp
	__lbeq	LL95
	__ldwi	2
	__stw	_spriteX
	__ldw	_spriteX
	  call	_spr_x
	__ldwi	2
	__lbra	LL73
LL95:

	  ldy	#0
	  call	_vsync
	__lbra	LL74
LL75:

	__ldwi	1
	__negw
	__lbra	LL73
LL73:

	  rts
	.endp

	.proc _move2
	__addmi	-2,__stack
	  call	_map2
	__stwi_s	0,0
LL97:

	__ldwi	8
	__pushw
	__ldwi	0
	  call	_joytrg
	__andws
	__notw
	__tstw
	__lbeq	LL98
	  ldy	#0
	  call	_satb_update
	__ldwi	0
	  call	_joy
	__andwi	128
	__tstw
	__lbeq	LL100
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	16
	  jsr	gtzp
LL100:

	__boolw
	__tstw
	__lbeq	LL99
	__ldw	_spriteX
	__subwi	1
	__stw	_spriteX
	__addwi	1
	__ldw_s	0
	__incw_s	0
	__ldw	_spriteX
	  call	_spr_x
LL99:

	__ldwi	0
	  call	_joy
	__andwi	32
	__tstw
	__lbeq	LL102
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	224
	  jsr	ltzp
LL102:

	__boolw
	__tstw
	__lbeq	LL101
	__ldw	_spriteX
	incw	_spriteX
	__ldw_s	0
	__incw_s	0
	__ldw	_spriteX
	  call	_spr_x
LL101:

	__ldwi	0
	  call	_joy
	__andwi	16
	__tstw
	__lbeq	LL104
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	16
	  jsr	gtzp
LL104:

	__boolw
	__tstw
	__lbeq	LL105
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	15
	  jsr	gtzp
LL105:

	__boolw
	__tstw
	__lbeq	LL106
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	225
	  jsr	ltzp
LL106:

	__boolw
	__tstw
	__lbeq	LL103
	__ldw	_spriteY
	__subwi	1
	__stw	_spriteY
	__addwi	1
	__ldw_s	0
	__incw_s	0
	__ldw	_spriteY
	  call	_spr_y
LL103:

	__ldwi	0
	  call	_joy
	__andwi	64
	__tstw
	__lbeq	LL108
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	225
	  jsr	ltzp
LL108:

	__boolw
	__tstw
	__lbeq	LL109
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	15
	  jsr	gtzp
LL109:

	__boolw
	__tstw
	__lbeq	LL107
	__ldw	_spriteY
	incw	_spriteY
	__ldw_s	0
	__incw_s	0
	__ldw	_spriteY
	  call	_spr_y
LL107:

	__ldw	_spriteY
	__stw	<__temp
	__ldwi	210
	  jsr	gtzp
	__lbeq	LL110
	__ldwi	3
	__stw	_spriteY
	__ldw	_spriteY
	  call	_spr_y
	__ldwi	3
	__lbra	LL96
LL110:

	__ldwi	0
	  call	_joy
	__andwi	128
	__tstw
	__lbeq	LL112
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	17
	  jsr	ltzp
LL112:

	__boolw
	__tstw
	__lbeq	LL113
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	62
	  jsr	gtzp
LL113:

	__boolw
	__tstw
	__lbeq	LL114
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	66
	  jsr	ltzp
LL114:

	__boolw
	__tstw
	__lbeq	LL111
	__ldw	_spriteX
	__subwi	1
	__stw	_spriteX
	__addwi	1
	__ldw_s	0
	__incw_s	0
	__ldw	_spriteX
	  call	_spr_x
LL111:

	__ldw	_spriteX
	__stw	<__temp
	__ldwi	1
	  jsr	ltzp
	__lbeq	LL115
	__ldwi	240
	__stw	_spriteX
	__ldw	_spriteX
	  call	_spr_x
	__ldwi	1
	__lbra	LL96
LL115:

	__ldw_s	0
	__pushw
	__ldwi	10
	  jsr	smod
	__notw
	__tstw
	__lbeq	LL116
	  call	_rand
	__pushw
	__ldwi	100
	  jsr	smod
	__pushw
	__ldw_s	2
	__pushw
	__ldwi	10
	  jsr	sdiv
	  jsr	lt
	__lbeq	LL117
	  ldy	#0
	  call	_spr_hide
	__ldwi	500
	__pushw
	__ldwi	2
	  jsr	sdiv
	__pushw
	__ldwi	50
	__pushw
	__ldwi	2
	  jsr	sdiv
	__pushw
	__ldwi	50
	__pushw
	__ldwi	3
	  jsr	sdiv
	__pushw
	__ldwi	30
	  call	_battle
	__stwi_s	0,0
	__ldwi	_spr_show
LL117:

LL116:

	  ldy	#0
	  call	_vsync
	__lbra	LL97
LL98:

	__ldwi	1
	__negw
	__lbra	LL96
LL96:

	__addmi	2,__stack
	  rts
	.endp

	.proc _move3
	  call	_map3
LL119:

	__ldwi	8
	__pushw
	__ldwi	0
	  call	_joytrg
	__andws
	__notw
	__tstw
	__lbeq	LL120
	  ldy	#0
	  call	_satb_update
	__ldwi	0
	  call	_joy
	__andwi	128
	__tstw
	__lbeq	LL122
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	16
	  jsr	gtzp
LL122:

	__boolw
	__tstw
	__lbeq	LL121
	__ldw	_spriteX
	__subwi	1
	__stw	_spriteX
	__addwi	1
	__ldw	_spriteX
	  call	_spr_x
LL121:

	__ldwi	0
	  call	_joy
	__andwi	32
	__tstw
	__lbeq	LL124
	__ldw	_spriteX
	__stw	<__temp
	__ldwi	224
	  jsr	ltzp
LL124:

	__boolw
	__tstw
	__lbeq	LL123
	__ldw	_spriteX
	incw	_spriteX
	__ldw	_spriteX
	  call	_spr_x
LL123:

	__ldwi	0
	  call	_joy
	__andwi	16
	__tstw
	__lbeq	LL125
	__ldw	_spriteY
	__subwi	1
	__stw	_spriteY
	__addwi	1
	__ldw	_spriteY
	  call	_spr_y
LL125:

	__ldwi	0
	  call	_joy
	__andwi	64
	__tstw
	__lbeq	LL127
	__ldw	_spriteY
	__stw	<__temp
	__ldwi	192
	  jsr	ltzp
LL127:

	__boolw
	__tstw
	__lbeq	LL126
	__ldw	_spriteY
	incw	_spriteY
	__ldw	_spriteY
	  call	_spr_y
LL126:

	__ldw	_spriteY
	__stw	<__temp
	__ldwi	1
	  jsr	ltzp
	__lbeq	LL128
	__ldwi	207
	__stw	_spriteY
	__ldw	_spriteY
	  call	_spr_y
	__ldwi	2
	__lbra	LL118
LL128:

	  ldy	#0
	  call	_vsync
	__lbra	LL119
LL120:

	__ldwi	1
	__negw
	__lbra	LL118
LL118:

	  rts
	.endp

	.proc _map1
	__addmi	-2,__stack
	  ldy	#0
	  call	_vsync
	  call	_cls
	__stbi_s	0,1
	load_sprites	#4096,_tilesgfx,#1
LL130:

	__ldb_s	1
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbeq	LL131
	__ldwi	258
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	1
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	1
	  call	_put_raw.3
	__ldwi	258
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	26
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	26
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL130
LL131:

	__stbi_s	2,1
LL132:

	__ldb_s	1
	__stw	<__temp
	__ldwi	27
	  jsr	ltzp
	__lbeq	LL133
	__ldwi	258
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	1
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldwi	1
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	258
	__phw	3,3
	__ldwi	30
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldwi	30
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL132
LL133:

	__stbi_s	2,1
LL134:

	__ldb_s	1
	__stw	<__temp
	__ldwi	29
	  jsr	ltzp
	__lbeq	LL135
	__stbi_s	2,0
LL136:

	__ldb_s	0
	__stw	<__temp
	__ldwi	26
	  jsr	ltzp
	__lbeq	LL137
	__ldwi	256
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldwi	257
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldwi	264
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldb_s	0
	__addwi	1
	  call	_put_raw.3
	__ldwi	265
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldb_s	0
	__addwi	1
	  call	_put_raw.3
	__ldb_s	0
	__addwi	2
	__stb_s	0
	__lbra	LL136
LL137:

	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL134
LL135:

	__ldwi	260
	__phw	3,3
	__ldwi	10
	__phb	1
	__ldwi	16
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	11
	__phb	1
	__ldwi	16
	  call	_put_raw.3
	__ldwi	268
	__phw	3,3
	__ldwi	10
	__phb	1
	__ldwi	17
	  call	_put_raw.3
	__ldwi	269
	__phw	3,3
	__ldwi	11
	__phb	1
	__ldwi	17
	  call	_put_raw.3
	__ldwi	260
	__phw	3,3
	__ldwi	30
	__phb	1
	__ldwi	8
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	8
	  call	_put_raw.3
	__ldwi	268
	__phw	3,3
	__ldwi	30
	__phb	1
	__ldwi	9
	  call	_put_raw.3
	__ldwi	269
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldwi	9
	  call	_put_raw.3
	_set_bgpal	#0,_tilespal,#1
LL129:

	__addmi	2,__stack
	  rts
	.endp

	.proc _map2
	__addmi	-2,__stack
	  ldy	#0
	  call	_vsync
	  call	_cls
	__stbi_s	0,1
	load_sprites	#4096,_tilesgfx,#1
LL139:

	__ldb_s	1
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbeq	LL140
	__ldwi	258
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	0
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	1
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	1
	  call	_put_raw.3
	__ldwi	258
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	26
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	26
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL139
LL140:

	__stbi_s	2,1
LL141:

	__ldb_s	1
	__stw	<__temp
	__ldwi	27
	  jsr	ltzp
	__lbeq	LL142
	__ldwi	258
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	1
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldwi	1
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	258
	__phw	3,3
	__ldwi	30
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldwi	30
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL141
LL142:

	__stbi_s	2,1
LL143:

	__ldb_s	1
	__stw	<__temp
	__ldwi	29
	  jsr	ltzp
	__lbeq	LL144
	__stbi_s	2,0
LL145:

	__ldb_s	0
	__stw	<__temp
	__ldwi	27
	  jsr	ltzp
	__lbeq	LL146
	__ldwi	256
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldwi	257
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldwi	264
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldb_s	0
	__addwi	1
	  call	_put_raw.3
	__ldwi	265
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldb_s	0
	__addwi	1
	  call	_put_raw.3
	__ldb_s	0
	__addwi	2
	__stb_s	0
	__lbra	LL145
LL146:

	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL143
LL144:

	__ldwi	260
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	8
	  call	_put_raw.3
	__ldwi	261
	__phw	3,3
	__ldwi	1
	__phb	1
	__ldwi	8
	  call	_put_raw.3
	__ldwi	268
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldwi	9
	  call	_put_raw.3
	__ldwi	269
	__phw	3,3
	__ldwi	1
	__phb	1
	__ldwi	9
	  call	_put_raw.3
	_set_bgpal	#0,_tilespal,#1
LL138:

	__addmi	2,__stack
	  rts
	.endp

	.proc _map3
	__addmi	-2,__stack
	  ldy	#0
	  call	_vsync
	  call	_cls
	__stbi_s	0,1
	load_sprites	#4096,_tilesgfx,#1
LL148:

	__ldb_s	1
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbeq	LL149
	__ldwi	258
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	26
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	26
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldwi	27
	  call	_put_raw.3
	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL148
LL149:

	__stbi_s	0,1
LL150:

	__ldb_s	1
	__stw	<__temp
	__ldwi	27
	  jsr	ltzp
	__lbeq	LL151
	__ldwi	258
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	1
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldwi	0
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldwi	1
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	258
	__phw	3,3
	__ldwi	30
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	259
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldb_s	1
	  call	_put_raw.3
	__ldwi	266
	__phw	3,3
	__ldwi	30
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldwi	267
	__phw	3,3
	__ldwi	31
	__phb	1
	__ldb_s	1
	__addwi	1
	  call	_put_raw.3
	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL150
LL151:

	__stbi_s	2,1
LL152:

	__ldb_s	1
	__stw	<__temp
	__ldwi	29
	  jsr	ltzp
	__lbeq	LL153
	__stbi_s	0,0
LL154:

	__ldb_s	0
	__stw	<__temp
	__ldwi	26
	  jsr	ltzp
	__lbeq	LL155
	__ldwi	256
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldwi	257
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldb_s	0
	  call	_put_raw.3
	__ldwi	264
	__phw	3,3
	__ldb_s	1
	__phb	1
	__ldb_s	0
	__addwi	1
	  call	_put_raw.3
	__ldwi	265
	__phw	3,3
	__ldb_s	1
	__addwi	1
	__phb	1
	__ldb_s	0
	__addwi	1
	  call	_put_raw.3
	__ldb_s	0
	__addwi	2
	__stb_s	0
	__lbra	LL154
LL155:

	__ldb_s	1
	__addwi	2
	__stb_s	1
	__lbra	LL152
LL153:

	_set_bgpal	#0,_tilespal,#1
LL147:

	__addmi	2,__stack
	  rts
	.endp

	.data
	.dw $0800
_titlegfx:
	.incchr "titletest.pcx",32,28
	.code
	.data
	.dw $0
_titlepal:
	.incpal "titletest.pcx"
	.code
	.data
	.dw $0
_titlebat:
	.incbat "titletest.pcx",4096,32,28
	.code
	.data
	.dw $0800
_screengfx:
	.incchr "screen.pcx",3,3
	.code
	.data
	.dw $0
_screenpal:
	.incpal "screen.pcx"
	.code
	.data
	.dw $0800
_tilesgfx:
	.incchr "tiles.pcx",8,8
	.code
	.data
	.dw $0
_tilespal:
	.incpal "tiles.pcx"
	.code
	.data
	.dw $0
_sprgfx:
	.incspr "sprite1.pcx",1,1
	.code
	.data
	.dw $0
_sprpal:
	.incpal "sprite1.pcx"
	.code
	.data
	.bank CONST_BANK
	.org $4000
LL0:
	.db	87,105,108,108,121,0,83,116
	.db	97,114,116,32,97,32,98,97
	.db	116,116,108,101,0,67,104,97
	.db	110,103,101,32,110,97,109,101
	.db	0,66,101,103,105,110,32,103
	.db	97,109,101,0,87,105,108,108
	.db	121,0,101,110,110,101,109,105
	.db	0,80,85,83,72,32,83,84
	.db	65,82,84,0,89,111,117,32
	.db	109,105,115,115,101,100,0,89
	.db	111,117,32,104,105,116,32,102
	.db	111,114,0,112,111,105,110,116
	.db	115,0,72,101,32,109,105,115
	.db	115,101,100,0,72,101,32,104
	.db	105,116,32,102,111,114,0,112
	.db	111,105,110,116,115,0,89,111
	.db	117,32,119,111,110,0,89,111
	.db	117,32,108,111,115,116,0,80
	.db	108,97,121,32,97,103,97,105
	.db	110,63,0,32,32,32,32,32
	.db	0,73,116,101,109,0,77,97
	.db	103,105,99,0,69,113,117,105
	.db	112,0,83,116,97,116,117,115
	.db	0

	.bss
_Entry:		.ds	6
_NamP1:		.ds	6
_DexP1:		.ds	1
_DexN:		.ds	1
_AtkP1:		.ds	1
_AtkN:		.ds	1
_DefP1:		.ds	1
_DefN:		.ds	1
_spriteX:		.ds	2
_spriteY:		.ds	2
__arg:

;0 error(s) in compilation
;	literal pool:185
;	constant pool:0
;	global pool:2016
;	Macro pool:1182
